app/urls.py
from django.urls import path
from app.views import*
app_name='something'
urlpatterns=[
    path('dhoni/',dhoni,name='dhoni'),
]

app1/urls.py
from django.urls import path
from app1.views import *
app_name='nothing'
urlpatterns=[
    path('virat/',virat,name='virat'),
]

project8/urls.py
from django.contrib import admin
from django.urls import path,include
import app,app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app1/',include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def dhoni(request):
    return render(request,'dhoni.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'virat.html')

templates/dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dhoni html page</title>
</head>
<body>
    <center>
        <h1> this is dhoni html page</h1>
        <h1>this page belongs to app</h1>
        <a href="{% url 'nothing:virat' %}">go to virat page</a>
    </center>
    
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>virat html page</title>
</head>
<body>
    <center>
        <h1> welcome to virat page</h1>
        <h1>this page belongs to app1</h1>
        <a href="{% url 'something:dhoni' %}">navigate to dhoni page</a>
    </center>
    
</body>
</html>